// ---------------------------------------------------------------------------
// Unified report template: single source of truth for UI and email.
//
// variant="ui"    -> Tailwind classes, dark mode, interactive elements
// variant="email" -> inline styles, single color scheme, static HTML
//
// Phase 4 introduces a new ReportData section structure (executiveSummary,
// marketSnapshot, developerSignals, signalInterpretation, supportingResources)
// alongside a `charts` payload populated by the runner. Legacy reports
// generated before Phase 4 still live in the database and are rendered by
// LegacyReportTemplate via the isLegacyReportData discriminator.
// ---------------------------------------------------------------------------

import {
	type EvaluationSummary,
	type ReportCharts,
	type ReportData,
	type SignalInterpretation,
	type SupportingResource,
	isLegacyReportData
} from '@pulsar/shared/types';
// React must remain a value import: when the pipeline package renders this
// template via renderToStaticMarkup, the JSX compiles to React.createElement
// calls that require React in runtime scope.
// biome-ignore lint/style/useImportType: see comment above
import React from 'react';
import { type LineSeries, renderLineSvg } from '../../lib/charts/line-svg';
import { type PieSlice, renderPieSvg } from '../../lib/charts/pie-svg';
import PulsarLogo from '../PulsarLogo';
import LegacyReportTemplate from './LegacyReportTemplate';

type V = 'ui' | 'email';

interface ReportTemplateProps {
	data: ReportData;
	variant: V;
	reportId: string;
	generatedAt?: string;
	reportUrl?: string;
	pdfUrl?: string;
	evaluationSummary?: EvaluationSummary;
	evalsUrl?: string;
}

// ---------------------------------------------------------------------------
// Style helper: returns className for UI, inline style for email.
// ---------------------------------------------------------------------------

function cx(v: V, ui: string, email: React.CSSProperties): Record<string, unknown> {
	return v === 'ui' ? { className: ui } : { style: email };
}

function renderBold(v: V, text: string): React.ReactNode[] {
	const parts = text.split(/\*\*(.+?)\*\*/g);
	return parts.map((part, i) =>
		i % 2 === 1 ? (
			<strong key={i} {...cx(v, 'text-gray-800 dark:text-neutral-200', { color: '#111827' })}>
				{part}
			</strong>
		) : (
			<span key={i}>{part}</span>
		)
	);
}

function renderParagraphs(v: V, text: string, style: 'body' | 'summary' = 'body'): React.ReactNode {
	const paragraphs = text.split('\n\n').filter((p) => p.trim());
	const props =
		style === 'summary'
			? cx(v, 'text-base leading-relaxed text-gray-700 dark:text-neutral-300', {
					lineHeight: '1.7',
					fontSize: '15px',
					color: '#374151',
					margin: '0 0 12px'
				})
			: cx(v, 'text-sm leading-relaxed text-gray-600 dark:text-neutral-400', {
					lineHeight: '1.7',
					fontSize: '14px',
					color: '#374151',
					margin: '0 0 12px'
				});

	return paragraphs.map((p, i) => (
		<p key={i} {...props}>
			{renderBold(v, p)}
		</p>
	));
}

function sectionWrap(v: V, children: React.ReactNode): React.ReactNode {
	return v === 'ui' ? (
		<div className="report-section rounded-lg border border-gray-200 dark:border-neutral-700 bg-white dark:bg-neutral-900 p-6">
			{children}
		</div>
	) : (
		<div style={{ padding: '0 24px 24px' }}>{children}</div>
	);
}

function sectionTitle(v: V, text: string): React.ReactNode {
	return (
		<h2
			{...cx(v, 'text-xl font-semibold text-gray-900 dark:text-neutral-100', {
				fontSize: '18px',
				fontWeight: 600,
				color: '#111827',
				margin: '0 0 12px'
			})}
		>
			{text}
		</h2>
	);
}

// ---------------------------------------------------------------------------
// Pie chart wrap, used inside Market Snapshot.
// ---------------------------------------------------------------------------

function MarketSnapshotPie({ v, charts }: { v: V; charts?: ReportCharts }) {
	const buckets = charts?.keywordDistribution?.buckets ?? [];
	if (buckets.length === 0) return null;

	// Drop the "Other" aggregate slice. The runner persists it for completeness
	// in the JSONB, but in the rendered pie it dominates the visual when the
	// long tail outweighs the named keywords. Show only the named top N.
	const namedBuckets = buckets.filter((b) => b.keyword.toLowerCase() !== 'other');
	if (namedBuckets.length === 0) return null;

	const slices: PieSlice[] = namedBuckets.map((b) => ({
		label: b.keyword,
		value: b.count,
		pct: b.pct
	}));
	const svg = renderPieSvg(slices, {
		width: 320,
		height: 320,
		legendPosition: 'right'
	});

	if (v === 'email') {
		return (
			<aside
				style={{
					float: 'left',
					width: '320px',
					marginRight: '20px',
					marginBottom: '12px'
				}}
				// biome-ignore lint/security/noDangerouslySetInnerHtml: SVG generated by trusted helper
				dangerouslySetInnerHTML={{ __html: svg }}
			/>
		);
	}

	return (
		<aside
			className="float-left mr-5 mb-3"
			style={{ width: '320px' }}
			// biome-ignore lint/security/noDangerouslySetInnerHtml: SVG generated by trusted helper
			dangerouslySetInnerHTML={{ __html: svg }}
		/>
	);
}

function ClearFloat() {
	return <div style={{ clear: 'both' }} />;
}

// ---------------------------------------------------------------------------
// Line chart wrap, full-width between Developer Signals and Signal
// Interpretation.
// ---------------------------------------------------------------------------

function CentralityLineChart({ v, charts }: { v: V; charts?: ReportCharts }) {
	const ec = charts?.entityCentrality;
	const series: LineSeries[] = (ec?.series ?? []).map((s) => ({
		name: s.entityName,
		points: s.points.map((p) => ({ x: p.period, y: p.centrality }))
	}));

	const svg = renderLineSvg(series, {
		width: 720,
		height: 240,
		yAxisLabel: 'Centrality'
	});

	const sparse =
		ec?.sparse === true || series.length === 0 || series.every((s) => s.points.length <= 1);

	const wrapStyle: React.CSSProperties = {
		margin: '0 auto',
		maxWidth: '720px',
		textAlign: 'center'
	};

	if (v === 'email') {
		return (
			<div style={{ padding: '0 24px 24px' }}>
				<div
					style={wrapStyle}
					// biome-ignore lint/security/noDangerouslySetInnerHtml: SVG generated by trusted helper
					dangerouslySetInnerHTML={{ __html: svg }}
				/>
				{sparse && (
					<p
						style={{
							fontSize: '12px',
							color: '#6b7280',
							textAlign: 'center',
							margin: '8px auto 0',
							maxWidth: '720px',
							fontStyle: 'italic'
						}}
					>
						Limited to current ingestion window. Historical depth fills in as backfill completes.
					</p>
				)}
			</div>
		);
	}

	return (
		<div className="report-section rounded-lg border border-gray-200 dark:border-neutral-700 bg-white dark:bg-neutral-900 p-6">
			<div
				className="mx-auto"
				style={{ maxWidth: '720px' }}
				// biome-ignore lint/security/noDangerouslySetInnerHtml: SVG generated by trusted helper
				dangerouslySetInnerHTML={{ __html: svg }}
			/>
			{sparse && (
				<p className="mx-auto mt-2 max-w-[720px] text-center text-xs italic text-gray-500 dark:text-neutral-400">
					Limited to current ingestion window. Historical depth fills in as backfill completes.
				</p>
			)}
		</div>
	);
}

// ---------------------------------------------------------------------------
// Signal Interpretation cards.
// ---------------------------------------------------------------------------

function InterpretationCard({
	v,
	interpretation
}: {
	v: V;
	interpretation: SignalInterpretation;
}) {
	const labelStyle: React.CSSProperties = {
		fontSize: '11px',
		fontWeight: 700,
		letterSpacing: '0.05em',
		textTransform: 'uppercase',
		color: '#6366f1',
		display: 'inline-block',
		marginRight: '8px',
		minWidth: '90px'
	};

	const rowStyle: React.CSSProperties = {
		fontSize: '14px',
		lineHeight: '1.6',
		color: '#374151',
		margin: '0 0 6px'
	};

	if (v === 'email') {
		return (
			<div
				style={{
					border: '1px solid #e5e7eb',
					borderLeft: '4px solid #6366f1',
					borderRadius: '0 8px 8px 0',
					padding: '12px 16px',
					marginBottom: '12px',
					background: '#fafafa'
				}}
			>
				<p style={rowStyle}>
					<span style={labelStyle}>Signal:</span>
					<span>{interpretation.signal}</span>
				</p>
				<p style={rowStyle}>
					<span style={labelStyle}>Meaning:</span>
					<span>{interpretation.meaning}</span>
				</p>
				<p style={{ ...rowStyle, margin: 0 }}>
					<span style={labelStyle}>Implication:</span>
					<span>{interpretation.implication}</span>
				</p>
			</div>
		);
	}

	const labelClass =
		'inline-block min-w-[90px] mr-2 text-[11px] font-bold uppercase tracking-wide text-indigo-600 dark:text-indigo-400';
	const rowClass = 'mb-1.5 text-sm leading-relaxed text-gray-700 dark:text-neutral-300';

	return (
		<div className="mb-3 rounded-r-lg border border-gray-200 dark:border-neutral-700 border-l-4 border-l-indigo-500 bg-gray-50 dark:bg-neutral-800/50 p-4">
			<p className={rowClass}>
				<span className={labelClass}>Signal:</span>
				<span className="text-gray-800 dark:text-neutral-200">{interpretation.signal}</span>
			</p>
			<p className={rowClass}>
				<span className={labelClass}>Meaning:</span>
				<span>{interpretation.meaning}</span>
			</p>
			<p className="m-0 text-sm leading-relaxed text-gray-700 dark:text-neutral-300">
				<span className={labelClass}>Implication:</span>
				<span>{interpretation.implication}</span>
			</p>
		</div>
	);
}

// ---------------------------------------------------------------------------
// Supporting Resources list.
// ---------------------------------------------------------------------------

function SupportingResourcesSection({
	v,
	resources
}: {
	v: V;
	resources: SupportingResource[];
}) {
	if (resources.length === 0) return null;

	if (v === 'email') {
		return (
			<ol style={{ margin: 0, padding: '0 0 0 20px' }}>
				{resources.map((r) => (
					<li key={r.url} style={{ marginBottom: '10px', lineHeight: '1.5' }}>
						<a
							href={r.url}
							style={{
								color: '#4f46e5',
								textDecoration: 'underline',
								fontWeight: 600,
								fontSize: '14px'
							}}
						>
							{r.title}
						</a>
						<div style={{ color: '#6b7280', fontSize: '13px', marginTop: '2px' }}>{r.why}</div>
					</li>
				))}
			</ol>
		);
	}

	return (
		<ol className="m-0 list-decimal space-y-3 pl-5">
			{resources.map((r) => (
				<li key={r.url} className="leading-snug">
					<a
						href={r.url}
						target="_blank"
						rel="noopener noreferrer"
						className="text-sm font-semibold text-indigo-600 hover:underline dark:text-indigo-400"
					>
						{r.title}
					</a>
					<div className="mt-0.5 text-sm text-gray-600 dark:text-neutral-400">{r.why}</div>
				</li>
			))}
		</ol>
	);
}

// ---------------------------------------------------------------------------
// Header and PDF export button (shared with the legacy template visually).
// ---------------------------------------------------------------------------

function ReportHeader({ v, generatedAt }: { v: V; generatedAt?: string }) {
	const reportDate = new Date(generatedAt || Date.now()).toLocaleDateString('en-US', {
		weekday: 'long',
		month: 'long',
		day: 'numeric',
		year: 'numeric'
	});

	return (
		<div
			{...cx(
				v,
				'report-header flex items-center justify-between gap-4 rounded-t-lg bg-gradient-to-r from-indigo-600 to-purple-600 p-8 text-white',
				{
					background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)',
					padding: '28px 24px',
					borderRadius: '12px 12px 0 0',
					display: 'flex',
					alignItems: 'center',
					justifyContent: 'space-between',
					gap: '16px'
				}
			)}
		>
			<div>
				<h1
					{...cx(v, 'text-2xl font-bold', {
						color: 'white',
						margin: 0,
						fontSize: '24px',
						fontWeight: 700
					})}
				>
					Pulsar: Market Analysis Report
				</h1>
				<p
					{...cx(v, 'mt-2 text-indigo-100', {
						color: 'rgba(255,255,255,0.8)',
						margin: '8px 0 0',
						fontSize: '14px'
					})}
				>
					{reportDate}
				</p>
			</div>
			<PulsarLogo
				className={v === 'ui' ? 'h-12 w-12 flex-shrink-0' : undefined}
				color="white"
				{...(v === 'email' ? { width: 48, height: 48, style: { flexShrink: 0 } } : {})}
			/>
		</div>
	);
}

function ExportPdfButton({ reportId }: { reportId: string }) {
	return (
		<div className="no-print group fixed bottom-6 right-6 z-40">
			<span className="pointer-events-none absolute right-full top-1/2 mr-3 -translate-y-1/2 whitespace-nowrap rounded-md bg-gray-900 dark:bg-neutral-700 px-2.5 py-1.5 text-xs font-medium text-white opacity-0 transition-opacity group-hover:opacity-100">
				Export PDF
			</span>
			<a
				href={`/api/reports/${reportId}/export/pdf`}
				aria-label="Export PDF"
				className="flex h-12 w-12 items-center justify-center rounded-full bg-indigo-600 text-white shadow-lg transition hover:bg-indigo-700"
			>
				<svg
					className="h-5 w-5"
					fill="none"
					viewBox="0 0 24 24"
					stroke="currentColor"
					strokeWidth={1.75}
				>
					<path
						strokeLinecap="round"
						strokeLinejoin="round"
						d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3"
					/>
				</svg>
			</a>
		</div>
	);
}

// ---------------------------------------------------------------------------
// New-shape report renderer.
// ---------------------------------------------------------------------------

function NewReportTemplate({
	data,
	variant: v,
	reportId,
	generatedAt,
	reportUrl,
	pdfUrl,
	evalsUrl
}: ReportTemplateProps) {
	const sections = data.sections;
	const charts = data.charts;

	if (!sections) {
		return (
			<p {...cx(v, 'text-gray-500 dark:text-neutral-400', { color: '#6b7280' })}>
				This report is missing its rendered sections.
			</p>
		);
	}

	return (
		<>
			<ReportHeader v={v} generatedAt={generatedAt} />
			{v === 'ui' && <ExportPdfButton reportId={reportId} />}

			{/* Executive Summary */}
			{sections.executiveSummary?.text &&
				sectionWrap(
					v,
					<>
						{sectionTitle(v, 'Executive Summary')}
						<div {...cx(v, 'mt-4 space-y-3', { marginTop: '12px' })}>
							{renderParagraphs(v, sections.executiveSummary.text, 'summary')}
						</div>
					</>
				)}

			{/* Market Snapshot, with pie chart floated left */}
			{sections.marketSnapshot?.text &&
				sectionWrap(
					v,
					<>
						{sectionTitle(v, 'Market Snapshot')}
						<MarketSnapshotPie v={v} charts={charts} />
						<div {...cx(v, 'mt-2 space-y-3', { marginTop: '8px' })}>
							{renderParagraphs(v, sections.marketSnapshot.text)}
						</div>
						<ClearFloat />
					</>
				)}

			{/* Developer Signals */}
			{sections.developerSignals?.text &&
				sectionWrap(
					v,
					<>
						{sectionTitle(v, 'Developer Signals')}
						<div {...cx(v, 'mt-4 space-y-3', { marginTop: '12px' })}>
							{renderParagraphs(v, sections.developerSignals.text)}
						</div>
					</>
				)}

			{/* Centrality line chart, full width */}
			<CentralityLineChart v={v} charts={charts} />

			{/* Signal Interpretation */}
			{sections.signalInterpretation &&
				sectionWrap(
					v,
					<>
						{sectionTitle(v, 'Signal Interpretation')}
						{sections.signalInterpretation.text && (
							<div {...cx(v, 'mt-4 mb-4 space-y-3', { marginTop: '12px', marginBottom: '16px' })}>
								{renderParagraphs(v, sections.signalInterpretation.text)}
							</div>
						)}
						{sections.signalInterpretation.interpretations?.map((interp, i) => (
							<InterpretationCard key={i} v={v} interpretation={interp} />
						))}
					</>
				)}

			{/* Supporting Resources */}
			{sections.supportingResources?.resources?.length > 0 &&
				sectionWrap(
					v,
					<>
						{sectionTitle(v, 'Supporting Resources')}
						<SupportingResourcesSection v={v} resources={sections.supportingResources.resources} />
					</>
				)}

			{/* Email-only CTAs */}
			{v === 'email' && reportUrl && (
				<div style={{ padding: '16px 24px 28px', textAlign: 'center' }}>
					<a
						href={reportUrl}
						style={{
							display: 'inline-block',
							background: '#4f46e5',
							color: 'white',
							padding: '12px 24px',
							borderRadius: '8px',
							textDecoration: 'none',
							fontWeight: 600,
							marginRight: '8px'
						}}
					>
						View Full Report
					</a>
					{pdfUrl && (
						<a
							href={pdfUrl}
							style={{
								display: 'inline-block',
								background: '#f3f4f6',
								color: '#374151',
								padding: '12px 24px',
								borderRadius: '8px',
								textDecoration: 'none',
								fontWeight: 600,
								marginRight: '8px'
							}}
						>
							Download PDF
						</a>
					)}
					{evalsUrl && (
						<a
							href={evalsUrl}
							style={{
								display: 'inline-block',
								background: '#f3f4f6',
								color: '#374151',
								padding: '12px 24px',
								borderRadius: '8px',
								textDecoration: 'none',
								fontWeight: 600
							}}
						>
							View Scores
						</a>
					)}
				</div>
			)}
		</>
	);
}

// ---------------------------------------------------------------------------
// Top-level dispatcher.
// ---------------------------------------------------------------------------

export default function ReportTemplate(props: ReportTemplateProps) {
	if (isLegacyReportData(props.data)) {
		return <LegacyReportTemplate {...props} />;
	}
	return <NewReportTemplate {...props} />;
}
